apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: componentsubscription-sample
  namespace: ocm-system
spec:
  source:
    secretRef:
      name: creds
    url: oci://ghcr.io/mohammad-ammar14
  destination:
    secretRef:
      name: destination-access-secret
    url: oci://ghcr.io/sidhishruti22
  component: "github.com/ammar/que"
  interval: 10m0s
  semver: "~v1.0.1"
  verify:
    - signature:
        name: alice
        key:
          name: alice-publickey
status:
  latestVersion: "v1.0.1"
  replicatedVersion: "v1.0.1"